<a href="https://colab.research.google.com/github/rameshpolaveni2576/python-basics-assignment/blob/main/Numpy_Array_assignment_session2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
#TASK 1
import numpy as np
np.random.seed(42)
no_of_students=10
names=np.random.choice(["Ramesh","Anil","Anusha","Rivansh","Vrushali"],no_of_students)
age=np.random.randint(15,18,no_of_students)
maths=np.random.randint(40,100,no_of_students)
science=np.random.randint(40,100,no_of_students)
english=np.random.randint(40,100,no_of_students)
marks=np.array([maths,science,english]).T
#print(marks)
print(marks.shape)
print(marks.dtype)


[[61 54 46]
 [83 86 60]
 [64 90 48]
 [88 83 78]
 [66 94 57]
 [98 91 43]
 [81 96 64]
 [67 42 99]
 [99 76 53]
 [55 90 89]]
(10, 3)
int64


In [33]:
marks_reshaped=marks.reshape(2,5,3)
print(marks_reshaped)
marks_sliced=marks[0:5,0:2]
print(marks_sliced)
# Shape (2, 5, 3) means the marks are organized into 2 groups (blocks), each with 5 students (rows), and each student has 3 subject marks (columns). It’s a 3D NumPy array.


[[[61 54 46]
  [83 86 60]
  [64 90 48]
  [88 83 78]
  [66 94 57]]

 [[98 91 43]
  [81 96 64]
  [67 42 99]
  [99 76 53]
  [55 90 89]]]
[[61 54]
 [83 86]
 [64 90]
 [88 83]
 [66 94]]


In [53]:
with open("student_records.txt","w") as file:
  file.write("name | age | maths | science | english\n")
  for i in range(no_of_students):
    file.write(f"{names[i]} | {age[i]} | {maths[i]} | {science[i]} | {english[i]}\n")
  print("records written successfully\n")
with open("student_records.txt", "r") as file:
  print(file.read())

records written successfully

name | age | maths | science | english
Rivansh | 17 | 61 | 54 | 46
Vrushali | 16 | 83 | 86 | 60
Anusha | 15 | 64 | 90 | 48
Vrushali | 16 | 88 | 83 | 78
Vrushali | 16 | 66 | 94 | 57
Anil | 16 | 98 | 91 | 43
Anusha | 16 | 81 | 96 | 64
Anusha | 15 | 67 | 42 | 99
Anusha | 15 | 99 | 76 | 53
Vrushali | 16 | 55 | 90 | 89

