<a href="https://colab.research.google.com/github/rameshpolaveni2576/python-basics-assignment/blob/main/practice_numpy_25thapril2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
numarr=np.array([1,2,3,4,5,6])
numarr_2=np.array([7,8,9,10,11,12])
print(numarr**numarr_2)
print(type(numarr+numarr_2))

[         1        256      19683    1048576   48828125 2176782336]
<class 'numpy.ndarray'>


In [17]:
print(np.zeros((3,4)))
print(np.zeros((3,4,5)))
print(np.ones((3,4,1,2)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[[[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]]


 [[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]]


 [[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]]]


In [27]:

arange_fun=np.arange(1,10,2)
print(arange_fun)

[1 3 5 7 9]


In [34]:
linspace_fun=np.linspace(1,10,1001)
print(linspace_fun)

[ 1.     1.009  1.018 ...  9.982  9.991 10.   ]


In [42]:
arr_rams = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_rams.shape)
print(arr_rams.ndim)
print(arr_rams.size)
print(arr_rams)
print(arr_rams[1,2])
print(arr_rams[0:2,1:3])

(2, 3)
2
6
[[1 2 3]
 [4 5 6]]
6
[[2 3]
 [5 6]]


In [71]:
arr_rams_1 = np.array([[1, 2, 3,4], [5, 6,7,8],[9,10,11,12]])
print(arr_rams_1.shape)
print(arr_rams_1.ndim)
print(arr_rams_1.size)
print(arr_rams_1)
print(arr_rams_1.reshape(-1,2))
print(arr_rams_1.T)

(3, 4)
2
12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
