<a href="https://colab.research.google.com/github/rameshpolaveni2576/python-basics-assignment/blob/main/random_numbers_generate_using_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

random numbers generations using Numpy Practice

In [16]:
import numpy as np
exe1=np.random.randint(1,100,5)
print(exe1)

[30 28 61 53 97]


In [24]:
exe3=np.random.randint(1,100,(3,4))
print(exe3)

[[39 33 37 77]
 [87 18 31 71]
 [33 23 75 83]]


In [23]:
exe2=np.random.randint(1,100,(5,5,5))
print(exe2)

[[[51 27 92 24 51]
  [25  9 82 88 46]
  [74 97 79 65 22]
  [30 95 49 98 27]
  [ 3 10 98 13 79]]

 [[44 77 25 78 13]
  [18 21 77 12 12]
  [33 88 62 50 23]
  [91 24 48 71 18]
  [80 18 22 71 95]]

 [[28 68 40 83 99]
  [67 29 91 58 53]
  [ 2 53 67 51 70]
  [85 32 90 43 49]
  [86 60 50 32 46]]

 [[54 65 23 37 82]
  [57 24 63 27 39]
  [ 1 88 53  9 90]
  [54 57 18 12 18]
  [72 30 30 86 52]]

 [[15 25 40 34 39]
  [23 53 51 90 38]
  [30 92 78 36 18]
  [83 50 21 94 62]
  [72 14 74 68 38]]]


Float value random generation

In [42]:
exe4=np.random.random(5)
print(exe4)

[0.6115628  0.35060127 0.11512728 0.78315778 0.05413119]


In [45]:
exe5=np.random.uniform(10,20,4)
print(exe5)

[11.48467764 13.36303644 15.44942695 16.80080042]


In [62]:
np.random.choice(exe1,10)

array([28, 53, 53, 30, 97, 97, 30, 28, 28, 30])

In [71]:
cities=np.array(["Delhi","Mumbai","Kolkatha","Hyderabad","Karimnagar","Warangal"])
cities_choice=np.random.choice(cities,2)
print(cities_choice)

['Hyderabad' 'Mumbai']


In [81]:
cities_choice_withoutduplicate=np.random.choice(cities,6,replace=False)
print(cities_choice_withoutduplicate)

['Karimnagar' 'Warangal' 'Mumbai' 'Delhi' 'Hyderabad' 'Kolkatha']


Seed parameter

In [86]:
print(np.array(["King","Queen","Jockey","ACE","Two","Three",
                "Four","Five","Six","Seven","Eight","Nine","Ten"]))

['King' 'Queen' 'Jockey' 'ACE' 'Two' 'Three' 'Four' 'Five' 'Six' 'Seven'
 'Eight' 'Nine' 'Ten']


In [100]:
deckofcards=np.array(["King","Queen","Jockey","ACE","Two","Three",
                "Four","Five","Six","Seven","Eight","Nine","Ten"])
np.random.seed(4)
np.random.shuffle(deckofcards)
print(deckofcards)

['ACE' 'Two' 'Four' 'Ten' 'Seven' 'Jockey' 'King' 'Nine' 'Six' 'Queen'
 'Three' 'Five' 'Eight']
